require('symbols-outline').setup({
    highlight_hovered_item = true,
    show_guides = true,
    auto_preview = false,
    position = 'right',
    keymaps = {
        close = {"<Esc>", "q"},
        goto_location = "<Cr>",
        focus_location = "o",
        hover_symbol = "<C-space>",
        toggle_preview = "K",
        rename_symbol = "r",
        code_actions = "a",
        fold = {"h", "-", "<Left>"},
        unfold = {"l", "+", "<Right>"},
        fold_all = "W",
        unfold_all = "E",
        fold_reset = "R",
        show_help = "?",
    },
    lsp_blacklist = {},
    symbol_blacklist = {},
    symbols = {
        File = {icon = "", hl = "@text.uri"},
        Module = {icon = "", hl = "@namespace"},
        Namespace = {icon = "", hl = "@namespace"},
        Package = {icon = "", hl = "@namespace"},
        Class = {icon = "", hl = "@type"},
        Method = {icon = "ƒ", hl = "@method"},
        Property = {icon = "", hl = "@method"},
        Field = {icon = "", hl = "@field"},
        Constructor = {icon = "", hl = "@constructor"},
        Enum = {icon = "了", hl = "@type"},
        Interface = {icon = "ﰮ", hl = "@type"},
        Function = {icon = "", hl = "@function"},
        Variable = {icon = "", hl = "@constant"},
        Constant = {icon = "", hl = "@constant"},
        String = {icon = "", hl = "@string"},
        Number = {icon = "#", hl = "@number"},
        Boolean = {icon = "⊨", hl = "@boolean"},
        Array = {icon = "", hl = "@constant"},
        Object = {icon = "", hl = "@type"},
        Key = {icon = "", hl = "@type"},
        Null = {icon = "NULL", hl = "@type"},
        EnumMember = {icon = "", hl = "@field"},
        Struct = {icon = "", hl = "@type"},
        Event = {icon = "", hl = "@type" },
        Operator = { icon = "+", hl = "@operator" },
        TypeParameter = { icon = "𝙏", hl = "@parameter" },
        Component = { icon = "", hl = "@function" },
        Fragment = { icon = "", hl = "@constant" },
    },
})

vim.keymap.set("n", "<leader>o", vim.cmd.SymbolsOutlineOpen, { noremap = true, silent = true })
